export interface GetUserObject {
  id: number;
  role_id: number;
  name: string;
  email: string;
  email_verified_at: string;
  created_at: string;
  updated_at: string;
  stripe_id: string;
  pm_type: string | null;
  pm_last_four: string | null;
  trial_ends_at: string | null;
  deleted_at: string | null;
  blocked: "0" | "1";
  should_logout: number;
  app_version: string;
  platform: string;
  limit_forced: number;
  business_name: string | null;
  business_address: string | null;
  phone_number: string | null;
  parent_id: number | null;
  status: number;
  image_url: string | null;
  created_by_id: number | null;
  referral: string | null;
  last_login_at: string;
  last_request_at: string;
  display_name: string | null;
  call_block: number;
  minutes_limit: number | null;
  postpaid_enable: number;
  postpaid_limit: string;
  number_allowed: number;
  day_purchase_limit: number;
  sms_block: number;
  pricing_tier_id: number | null;
  stripe_count: number;
  stripe_cost: string;
  affiliate_promo_code_id: number | null;
  un_subscribe: number;
  balance: number;
}
