import { ThemeProvider } from "@/components/layout/ThemeProvider";
import { AuthProvider } from "@/providers/AuthProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Sora, Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { DateRangeProvider } from "@/providers/DateRangeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable}  ${sora.variable} antialiased text-body font-sora`}
        suppressHydrationWarning
      >
        <DateRangeProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AuthProvider>
              <ReactQueryProvider>
                {children}
                <Toaster richColors closeButton position="top-right" />
              </ReactQueryProvider>
            </AuthProvider>
          </ThemeProvider>
        </DateRangeProvider>
      </body>
    </html>
  );
}
